// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ainpncogvhckvqqsphrd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFpbnBuY29ndmhja3ZxcXNwaHJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1MTAyMzMsImV4cCI6MjA2MjA4NjIzM30.-H1iv2rX3906TPXONRrCEwHzDMdEX3olfU10-74AfzA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);